[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"
  
  # Base directory (root of repo)
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18.17.0"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200